// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulqnimmhknylzhbxvibw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVscW5pbW1oa255bHpoYnh2aWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyODkzODIsImV4cCI6MjA2NDg2NTM4Mn0.udsjIHg16F9I8y971EPxpxphaNGD-G2uDmrB56FtWvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});